### ISSUE TITLE
Source code isn't updated with latest release

### ISSUE THREAD

**Issue by ash-arr** [Mowjoh/Quasar#7]
Hey there, I've been curious to poke around with this mod to see if I could contribute, but it seems like the source code for 1.5.0.5 and 1.5.0 doesn't correspond to the software that is installed by QuasarSetup.msi. It seems to build the older app before it was re-written. Are there plans to release the code for the rewritten app? Am I mistaken? I am not experienced with C# so I apologize if I'm misunderstanding something here.

**Comment by Mowjoh** [comment]
Hello, There are two versions, one for the installer (which is used by the MSI to know if it has to update the files or not) and a version for the app itself, Quasar. This is on purpose so I can update the installation without changing Quasar's version itself.

As to release for the code, It's still on a separated local branch because I'm gonna change the data models and this will have effects through the whole app, so please wait a bit before it's release.
